[package]
name = "gallery_core"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.44", features = ["serde"] }
schemars = "1.2.1"
serde = { version = "1.0.228", features = ["derive"] }
